name: Build Vanitygen-Litecoin on Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSYS2 and required packages
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
              base-devel
              mingw-w64-x86_64-gcc
              mingw-w64-x86_64-openssl
              mingw-w64-x86_64-pcre
              make
              git

      - name: Build vanitygen-litecoin
        shell: msys2 {0}
        run: |
          make clean
          make V=1

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: vanitygen-litecoin
          path: vanitygen/vanitygen.exe
